import React from 'react';
const Veil = () =>{
  return (
    <article>
      <h1>Veil</h1>
      <figure>
        <img src={require('../images/veilApp.png')} alt="" />
      </figure>
      <p>Veil (2016) is spectral encryption software.</p>
      <p>It applies a monoalphabetic substitution cypher to scramble FFT bins.</p>
      <p>Audio can be descrambled using a key generated by the software.</p>
      <p>The code repository for the project can be found <a target="_blank" rel="noreferrer" href="https://github.com/tmartinez88/Veil">here</a>.</p>
    </article>
  );
}
export default Veil;
