import React from 'react';
const Veil = () =>{
  return (
    <div className="main">
      <img src={require('../images/veilApp.png')}/>
      <br></br>
      <br></br>
      <p>Veil (2016) is spectral encryption software.</p>
      
      <p>It applies a monoalphabetic substitution cypher to scramble FFT bins.</p>
      
      <p>Audio can be descrambled using a key generated by the software.</p>
      
      <p>The code repository for the project can be found <a className = "link" target = "_blank" href="https://github.com/tmartinez88/Veil">here</a>.</p>
      
    </div>
  );
}
export default Veil;
